# -*- coding: utf-8 -*-
"""freqbasedKW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hGfSENmeVOM7KrcDw-uEMZHlaoYgeuK
"""

import nltk

from nltk.corpus import stopwords
from collections import Counter
from nltk.tokenize import word_tokenize
import time

# Download NLTK stopwords if not already downloaded
nltk.download()

def extract_keywords(blog_text):
    start_time = time.time()

    # Tokenize the text and lowercase
    words = word_tokenize(blog_text.lower())

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word.isalnum() and word not in stop_words]

    # Calculate word frequency
    word_freq = Counter(words)

    # Get top 5 keywords based on frequency
    top_keywords = [word for word, _ in word_freq.most_common(5)]

    end_time = time.time()
    time_taken = end_time - start_time
    print(f"Time taken: {time_taken:.4f} seconds")

    return top_keywords

blog_text = """
    Machine learning is a branch of artificial intelligence that focuses on the development of algorithms allowing computers to learn from and make decisions based on data. It encompasses supervised learning, unsupervised learning, and reinforcement learning. Applications range from image recognition to natural language processing, revolutionizing industries like healthcare and finance.
    """

keywords = extract_keywords(blog_text)
print("Keywords:", keywords)


# results

# Time taken: 0.0118 seconds
# Keywords: ['learning', 'machine', 'branch', 'artificial', 'intelligence']