# -*- coding: utf-8 -*-
"""Spacy_method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojiCm1WB4fUEHXxvMuMEmE1CLec3e4hp
"""

!pip install spacy

!python -m spacy download en_core_web_sm

import spacy
from collections import Counter
import time

def extract_keywords_dependency_parsing(blog_text):
    start_time = time.time()

    # Load spaCy model for English
    nlp = spacy.load("en_core_web_sm")

    # Process the blog text
    doc = nlp(blog_text)

    # Extract nouns and adjectives connected by certain dependency relations
    keywords = []
    for token in doc:
        if token.pos_ in ['NOUN', 'PROPN', 'ADJ']:  # Consider nouns, proper nouns, and adjectives
            if token.dep_ in ['amod', 'compound']:  # Consider adjectival modifiers and compound relations
                keywords.append(token.text.lower())

    # Calculate word frequency
    word_freq = Counter(keywords)

    # Get top 5 keywords based on frequency
    top_keywords = [word for word, _ in word_freq.most_common(5)]

    end_time = time.time()
    time_taken = end_time - start_time
    print(f"Time taken: {time_taken:.4f} seconds")

    return top_keywords

# blog with exactly 512 chars
blog_text = """
    Machine learning is a branch of artificial intelligence that focuses on the development of algorithms allowing computers to learn from and make decisions based on data. It encompasses supervised learning, unsupervised learning, and reinforcement learning. Applications range from image recognition to natural language processing, revolutionizing industries like healthcare and finance.
    """

keywords = extract_keywords_dependency_parsing(blog_text)
print("Keywords (Dependency Parsing):", keywords)

# result:
# Time taken: 0.6733 seconds
# Keywords (Dependency Parsing): ['machine', 'artificial', 'supervised', 'unsupervised', 'reinforcement']