# -*- coding: utf-8 -*-
"""suma _method_KW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4xxZd7e0NgV-PtHyF1cncyU7vpG3ZZ8
"""

!pip install summa

from summa import keywords
import time

def extract_keywords_textrank(blog_text):
    start_time = time.time()

    # Extract keywords using Textrank algorithm
    top_keywords = keywords.keywords(blog_text, words=5, split=True, scores=False)

    end_time = time.time()
    time_taken = end_time - start_time
    print(f"Time taken: {time_taken:.4f} seconds")

    return top_keywords

# Example usage:
# blog with exactly 512 chars
blog_text = """
    Machine learning is a branch of artificial intelligence that focuses on the development of algorithms allowing computers to learn from and make decisions based on data. It encompasses supervised learning, unsupervised learning, and reinforcement learning. Applications range from image recognition to natural language processing, revolutionizing industries like healthcare and finance.
    """

keywords = extract_keywords_textrank(blog_text)
print("Keywords (Textrank):", keywords)

# results:
# Time taken: 0.0580 seconds
# Keywords (Textrank): ['learning', 'learn', 'allowing', 'decisions', 'like', 'language']